on:
  push:
  pull_request:

name: website 

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup R from r-lib
      uses: r-lib/actions/setup-r@master

    - name: Setup pandoc from r-lib
      uses: r-lib/actions/setup-pandoc@master

    - name: Set up git 
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
      shell: bash {0}

    - name: Install libcurl
      run: |
        sudo apt-get install --no-install-recommends -y libcurl4-openssl-dev \
        libfreetype-dev libharfbuzz-dev libfribidi-dev libpng-dev libtiff-dev \
        libjpeg-dev

    - name: Deploy website
      run: |
        install.packages("remotes")
        remotes::install_github("r-lib/pkgdown")
        pkgdown::deploy_to_branch(new_process = FALSE)
      shell: Rscript {0}
