on:
  push:
  pull_request:

name: website 

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      r_version: 4.2
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup R from r-lib
      uses: r-lib/actions/setup-r@master
      with:
        r-version: ${{ env.r_version }}

    - name: Setup pandoc from r-lib
      uses: r-lib/actions/setup-pandoc@master

    - name: Install pkgdown
      run: |
        install.packages("remotes")
        library(remotes)
        remotes::install_cran("pkgdown", dependencies = TRUE)
      shell: Rscript {0}

    - name: Deploy website
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        Rscript -e "pkgdown::deploy_to_branch(new_process = FALSE)"
      shell: bash {0}
