on:
  push:
  pull_request:

name: website 

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup R from r-lib
      uses: r-lib/actions/setup-r@master

    - name: Setup pandoc from r-lib
      uses: r-lib/actions/setup-pandoc@master

    - name: Set up git 
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
      shell: bash {0}

    - name: Deploy website
      run: |
        install.packages("remotes")
        library("remotes")
        remotes::install_cran("pkgdown", dependencies = TRUE)
        library("pkgdown")
        pkgdown::deploy_to_branch(new_process = FALSE)
      shell: Rscript {0}
